name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: sudo apt-get install chromium-chromedriver
      
      - name: Copy configuration
        run: cp config.json.example config.json
      - name: Run tests
        run: npm run test

      - name: Upload results on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test-results